name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "59 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: LeetCode Sync Barnacle
        uses: humble-barnacle001/leetcode-sync@v0.1.0
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: problems
            
